Fix UnexpectedError with unnamed arguments
Some block variables do not have names.
```
->(*, **, &) do
  #=> UnexpectedError: undefined method `start_with?' for nil(NoMethodError)
  if false
  end
end
```
If a variable has no name, accept it as a parameter but exclude it since it is not needed for analysis